import tkinter as ari
window = ari.Tk()
window.title("Aries De Guzman's Profile")
window.geometry("600x600")
window.resizable(False,True)
window.configure(bg = "#d96f9e")
Label = ari.Label(window, text = "Student Profile", font = ("Times New Roman", 30, "bold"), bg = "#d96f9e")
Label.pack(pady=20)
Label = ari.Label(window, text = "Name: Aries De Guzman", font = ("Times New Roman", 15), bg = "#d96f9e")
Label.pack(anchor = "w", padx=20, pady=5)
Label = ari.Label(window, text = "Age: 18 years old", font = ("Times New Roman", 15), bg = "#d96f9e")
Label.pack(anchor = "w", padx=20, pady=5)
Label = ari.Label(window, text = "Course: BSIT", font = ("Times New Roman", 15), bg = "#d96f9e")
Label.pack(anchor = "w", padx=20, pady=5)
Label = ari.Label(window, text = "Birthday: July 10, 2007", font = ("Times New Roman", 15), bg = "#d96f9e")
Label.pack(anchor = "w", padx=20, pady=5)
Label = ari.Label(window, text = "Motto: Everything works out in the end", font = ("Times New Roman", 15), bg = "#d96f9e")
Label.pack(anchor = "w", padx=20, pady=5)
window.mainloop()